In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4], dtype='int16')
print(a)

[1 2 3 4]


In [5]:
b = np.array([[1.2,2.5], [6.5,4.2], [6.2,7.1]])
print(b)

[[1.2 2.5]
 [6.5 4.2]
 [6.2 7.1]]


In [6]:
print(a.ndim)

1


In [7]:
b.ndim

2

In [8]:
a.shape

(4,)

In [9]:
b.shape

(3, 2)

In [10]:
a.dtype

dtype('int16')

In [11]:
b.dtype

dtype('float64')

In [12]:
# itemsize - number of byte's one item takes
a.itemsize

2

In [13]:
b.itemsize

8

In [14]:
# size - number of elements, length of array
a.size

4

In [15]:
b.size

6

In [16]:
# Accessing and manipulating elements
c = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])

In [17]:
c[1, 3] # np.array[row, col]

np.int64(10)

In [18]:
c[1, :] # get array [row, :], ':' -> all the elements

array([ 7,  8,  9, 10, 11, 12])

In [19]:
c[:, 5]

array([ 6, 12])

In [20]:
c[1, 1:5:2] # [row, col] -> [startindex:endindex:steps]

array([ 8, 10])

In [21]:
c[0, 4] = 23
print(c)

[[ 1  2  3  4 23  6]
 [ 7  8  9 10 11 12]]


In [22]:
c[:, 1] = [234, 52]
print(c)

[[  1 234   3   4  23   6]
 [  7  52   9  10  11  12]]


In [23]:
c[:, 5] = 92
print(c)

[[  1 234   3   4  23  92]
 [  7  52   9  10  11  92]]


In [24]:
# 3D array
d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
d[1,0,:]

array([5, 6])

In [26]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [27]:
d[:,1,:] = [[8,8], [9,9]]
print(d)

[[[1 2]
  [8 8]]

 [[5 6]
  [9 9]]]


In [28]:
# All 0's and 1's
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
# other that 1's and 0's
np.full((2,3), 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [31]:
np.full_like(a, 7)

array([7, 7, 7, 7], dtype=int16)

In [32]:
# random decimal numbers
np.random.rand(4,2)

array([[0.35880991, 0.87271309],
       [0.75132851, 0.7993574 ],
       [0.80445682, 0.5166109 ],
       [0.66514414, 0.57597631]])

In [33]:
np.random.random_sample(c.shape)

array([[0.09596797, 0.10666639, 0.47121163, 0.54305461, 0.65683609,
        0.13823817],
       [0.56702051, 0.36903409, 0.67625588, 0.78780848, 0.77933746,
        0.45001051]])

In [34]:
# random integers
np.random.randint(10, size=(3,3))

array([[1, 8, 3],
       [8, 6, 1],
       [0, 3, 7]])

In [35]:
np.random.randint(-5, 5, size=(3,3))

array([[-4, -3,  0],
       [ 0, -3,  2],
       [-1,  3,  3]])

In [36]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [37]:
e = np.array([[1,2,3]])
r1 = np.repeat(e, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
f = np.ones((5,5))
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
f[1:4, 1:4] = 0
print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
f[2,2] = 9
print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
# right way of copying the arrays
g = np.array([1,2,3])

h = g
h[0] = 100
print(g) # [100, 2, 3]
print(h) # [100, 2, 3]
h[0] = 1

h = g.copy()
h[0] = 100
print(g) # [1, 2, 3] -> original array
print(h) # [100, 2, 3] -> copied array


[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


# Mathematics

In [42]:
math1 = np.array([1,2,3,4])
math1 + 2

array([3, 4, 5, 6])

In [43]:
math1 / 2

array([0.5, 1. , 1.5, 2. ])

In [44]:
math2 = np.array([9,8,7,6])
math1 + math2

array([10, 10, 10, 10])

In [45]:
math1 ** 2

array([ 1,  4,  9, 16])

In [46]:
np.sin(math1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [47]:
np.cos(math1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [48]:
la1 = np.ones((4,5))
la2 = np.full((5,2), 2)
print(la1)
print(la2)
np.matmul(la1, la2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

In [49]:
# Find the determinant
imat = np.identity(3)
print(imat)
np.linalg.det(imat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

#### Statistics

In [50]:
stat1 = np.array(([[1,2,3],[4,5,6]]))
print(stat1)

[[1 2 3]
 [4 5 6]]


In [51]:
np.min(stat1)

np.int64(1)

In [52]:
np.max(stat1)

np.int64(6)

In [53]:
np.min(stat1, axis=0) # axis = 0 -> check column by column

array([1, 2, 3])

In [54]:
np.min(stat1, axis=1) # axis = 1 -> check row by row

array([1, 4])

In [55]:
np.sum(stat1, axis=0)

array([5, 7, 9])

In [56]:
np.sum(stat1, axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [57]:
ra = np.array(([[1,2,3,4],[5,6,7,8]]))

In [58]:
ra2 = np.reshape(ra, (2,2,2))

In [59]:
print(ra)
print(ra2)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Vertical stacking of vectors
v1 = np.array(([1,2,3,4]))
v2 = np.array(([5,6,7,8]))
np.vstack([v1, v2, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [61]:
# Horizontal stacking of vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

#### Load data from file

In [62]:
# data = np.genfromtxt('data.txt', delimiter=';')
# print(data)
# data = a.astype('int32')
# print(data)

#### Boolean Masking and Advanced Indexing

In [63]:
# print(data>3)

# data[data>3]

In [64]:
advIdx = np.array(([1,2,3,4,5,6,7,8,9]))

In [65]:
# You can index with a list in numpy
advIdx[[0,4,8]]

array([1, 5, 9])

In [1]:
# check if any value element satisfies any condition
checkCondition = np.array(([[6,2,2,3,6,7], [1,3,6,8,2,3]]))
print(np.any(checkCondition>5, axis=1))
print(np.all(checkCondition>5, axis=0))
checkCondition[np.any(checkCondition>5, axis=1)]

[ True  True]
[False False False False False False]


array([[6, 2, 2, 3, 6, 7],
       [1, 3, 6, 8, 2, 3]])

In [1]:
### QUIZ
import numpy as np

q = np.array(([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20], [21,22,23,24,25],[26,27,28,29,30]]))
print(q)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [2]:
q[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [3]:
q[0:4:1, 1:5:1]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [4]:
(q[0:4, 1:5] * np.identity(4) > 0)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [5]:
qa = (q[0:4, 1:5] * np.identity(4) > 0)
print(qa)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [6]:
newq = q[0:4, 1:5]
print(q)
newq[qa]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([ 2,  8, 14, 20])

In [7]:
q[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])